# Generated by Django 5.2.4 on 2025-07-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticket',
            name='uq_ticket_qr_hash',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='qr_hash',
            field=models.CharField(editable=False, max_length=64, unique=True),
        ),
    ]
