# Generated by Django 5.2.4 on 2025-08-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_ticket_uq_ticket_qr_hash_alter_ticket_qr_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='tickets/'),
        ),
    ]
